//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaOtorgada { get; set; }
        public Nullable<int> duracion { get; set; }
        public int idMedico { get; set; }
        public int idPaciente { get; set; }
        public Nullable<System.DateTime> fechaRealizada { get; set; }
        public int idAsistenteRealizada { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
    }
}
