//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaOtorgada { get; set; }
        public Nullable<int> duracion { get; set; }
<<<<<<< HEAD
=======
        public Nullable<System.DateTime> fechaRealizada { get; set; }
>>>>>>> 2ee4d946bcc68d80eb8bbea04406c9ceb6ea2b33
        public string nombreMedico { get; set; }
        public string nombrePaciente { get; set; }
        public Nullable<System.DateTime> fechaRealizada { get; set; }
        public string nombreAsistenteRealizada { get; set; }
    }
}
