//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitas
    {
        public int id { get; set; }
        public System.DateTime FechaRealizada { get; set; }
        public string Motivo { get; set; }
        public string nombreMedico { get; set; }
        public string nombrePaciente { get; set; }
        public string Comentario { get; set; }
        public byte[] RecetaMedicamento { get; set; }
        public string FechaProxVisita { get; set; }
    }
}
